import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { Pseudo2GeneratedModule, Pseudo2GeneratedSharedModule } from './generated/module.js';
import { Pseudo2Validator, registerValidationChecks } from './pseudo2-validator.js';
//import { IndentationAwareTokenBuilder, IndentationAwareLexer } from 'langium';
import { IndentationAwareLexer, IndentationAwareTokenBuilder } from 'langium';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type Pseudo2AddedServices = {
    validation: {
        Pseudo2Validator: Pseudo2Validator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type Pseudo2Services = LangiumServices & Pseudo2AddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const Pseudo2Module: Module<Pseudo2Services, PartialLangiumServices & Pseudo2AddedServices> = {
  parser: {
    TokenBuilder: () => new IndentationAwareTokenBuilder({
      ignoreIndentationDelimiters: [
        ['(', ')'],
        ['[', ']'],
        ['{', '}']
      ]
    }),
    Lexer: services => new IndentationAwareLexer(services)
  },
  validation: {
    Pseudo2Validator: () => new Pseudo2Validator()
  }
};


/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPseudo2Services(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Pseudo2: Pseudo2Services
} {
    const shared = inject(
        createDefaultSharedModule(context),
        Pseudo2GeneratedSharedModule
    );
    const Pseudo2 = inject(
        createDefaultModule({ shared }),
        Pseudo2GeneratedModule,
        Pseudo2Module
    );
    shared.ServiceRegistry.register(Pseudo2);
    registerValidationChecks(Pseudo2);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Pseudo2 };
}
