import { inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule } from 'langium/lsp';
import { Pseudo2GeneratedModule, Pseudo2GeneratedSharedModule } from './generated/module.js';
import { Pseudo2Validator, registerValidationChecks } from './pseudo2-validator.js';
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const Pseudo2Module = {
    validation: {
        Pseudo2Validator: () => new Pseudo2Validator()
    }
};
/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPseudo2Services(context) {
    const shared = inject(createDefaultSharedModule(context), Pseudo2GeneratedSharedModule);
    const Pseudo2 = inject(createDefaultModule({ shared }), Pseudo2GeneratedModule, Pseudo2Module);
    shared.ServiceRegistry.register(Pseudo2);
    registerValidationChecks(Pseudo2);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Pseudo2 };
}
//# sourceMappingURL=hello-world-module.js.map