/**
 * @file pseudo2-module.d.ts
 * @brief Deklariert die öffentliche Service-Oberfläche des Pseudo2-Langium-Moduls.
 * @author Abdul
 */

import { type Module } from 'langium';
import { type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { Pseudo2Validator } from './pseudo2-validator.js';
/**
 * Declaration of custom services - add your own service classes here.
 */
export type Pseudo2AddedServices = {
    /** Sprachspezifische Validierungsdienste. */
    validation: {
        /** Gemeinsame Instanz des semantischen Pseudo2-Validators. */
        Pseudo2Validator: Pseudo2Validator;
    };
};
/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type Pseudo2Services = LangiumServices & Pseudo2AddedServices;
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */


/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 *
 * Die Funktion kombiniert Langiums Standardmodule, die generierten Pseudo2-Module
 * und die benutzerdefinierte Validatorbindung zu einem vollständig verwendbaren
 * Servicegraphen für CLI, Tests, Webeditor und Language Server.
 */




export declare function createPseudo2Services(context: DefaultSharedModuleContext): {
    /** Dokument- und LSP-übergreifende Langium-Dienste. */
    shared: LangiumSharedServices;
    /** Sprachspezifische Pseudo2-Dienste. */
    Pseudo2: Pseudo2Services;
};
